channels:
  - conda-forge

dependencies:
  - dask
  - ipykernel
  - matplotlib
  - nbstripout
  - numpy
  - pandas
  - pre-commit
  - python-graphviz
  - python=3.9
  - pytorch
  - scikit-learn
  - seaborn
  - tensorboard
  - torchmetrics
  - torchvision
